#!/bin/sh
#
# Copyright (c) 2015 Davide Guerri <davide.guerri@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

get_ip_addresses() {
    local ifname addr
    for net in /sys/class/net/*; do
        ifname=$(basename "$net")
        if [ "$ifname" != 'lo' ]; then
            addr="$(/sbin/ifconfig "$ifname" | grep 'inet addr' \
                | awk '{ print $2 }' | awk -F: '{ print $2 }')"
            printf "%13s: %s\n" "$ifname" "$addr"
        fi
    done
}

if [ "$METHOD" = loopback ]; then
    exit 0
fi

# Only run from ifup.
if [ "$MODE" != start ]; then
    exit 0
fi

if [ -f /etc/issue-original ]; then
    cp /etc/issue-original /etc/issue
else
    cp /etc/issue /etc/issue-original
fi

get_ip_addresses >> /etc/issue
echo "" >> /etc/issue
